security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: admin_dashboard
                enable_csrf: true
            logout:
                path: app_logout
                target: app_landing_public
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }    # Accès au dashboard admin
        - { path: ^/matchs, roles: ROLE_USER }    # Accès aux matchs pour les users
        - { path: ^/tournois, roles: ROLE_USER }  # Accès aux tournois pour les users
        - { path: ^/login, roles: PUBLIC_ACCESS } # Page de connexion accessible à tous
        - { path: ^/, roles: PUBLIC_ACCESS }      # Landing accessible à tous

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                migrate_from: null
                cost: 4
                time_cost: 3
                memory_cost: 10
