security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_home  # ✅ Redirection après connexion

            logout:
                path: app_logout
                target: app_home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]  # ✅ Un admin a automatiquement les permissions d’un user

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }    # ✅ Admin uniquement
        - { path: ^/matchs, roles: ROLE_USER }    # ✅ Matchs accessibles aux utilisateurs connectés
        - { path: ^/tournois, roles: ROLE_USER }  # ✅ Tournois accessibles aux utilisateurs connectés
        - { path: ^/login, roles: PUBLIC_ACCESS } # ✅ Page de connexion accessible à tous
        - { path: ^/, roles: PUBLIC_ACCESS }      # ✅ Landing accessible à tous

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                migrate_from: null
                cost: 4
                time_cost: 3
                memory_cost: 10
